name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: train-bot
  steps:
    - name: Run Spec Images
      run: spec_images.py
  
#jobs:
#  run-python:
#    steps:
#    - name: Checkout Code
#      uses: actions/checkou@v3#

#    - name: Setup Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.11'
    
#    - name: Run Python Script
#      run: spec_images.py

